name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Update Config with GitHub Secret
        run: |
          echo ${{ secrets.CONFIG }} | base64 --decode > shared/src/commonMain/kotlin/com/paulcoding/tmdb/Config.kt 

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Android APK
        run: ./gradlew androidApp:assembleRelease

      - name: Sign APK
        id: sign_app
        uses: ilharp/sign-android-release@nightly
        with:
          releaseDir: androidApp/build/outputs/apk/release
          signingKey: ${{ secrets.SIGNING_KEY }}
          keyAlias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          buildToolsVersion: ${{ env.ANDROID_BUILD_TOOLS_VERSION }}

      - name: Rename apks
        run: |
          cp ${{ env.ANDROID_SIGNED_FILE }} ./TMDB.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: tmdb-apk
          path: ./TMDB.apk
          retention-days: 30